db.url=jdbc:mysql://examination-examination.c.aivencloud.com:18314/examination_management_system?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=avnadmin
db.password=<YOUR_AIVEN_PASSWORD>
db.driver=com.mysql.cj.jdbc.Driver
